CREATE DATABASE PARTS;
USE PARTS;
CREATE TABLE PARTTABLE(
P_ID VARCHAR(50),
PNAME VARCHAR(60),
COLOUR VARCHAR(60),
WEIGHT INT,
CITY VARCHAR(50)
);
ALTER TABLE `parts`.`parttable` 
CHANGE COLUMN `P_ID` `P_ID` VARCHAR(50) NOT NULL ,
CHANGE COLUMN `PNAME` `PNAME` VARCHAR(60) NOT NULL ,
CHANGE COLUMN `COLOUR` `COLOUR` VARCHAR(60) NOT NULL ,
CHANGE COLUMN `WEIGHT` `WEIGHT` INT NOT NULL ,
CHANGE COLUMN `CITY` `CITY` VARCHAR(50) NOT NULL ,
ADD PRIMARY KEY (`P_ID`),
ADD UNIQUE INDEX `P_ID_UNIQUE` (`P_ID` ASC) VISIBLE;
;
INSERT INTO `parts`.`parttable` (`P_ID`, `PNAME`, `COLOUR`, `WEIGHT`, `CITY`) VALUES ('P1', 'NUT', 'RED', '12', 'LONDON');
INSERT INTO `parts`.`parttable` (`P_ID`, `PNAME`, `COLOUR`, `WEIGHT`, `CITY`) VALUES ('P2', 'BOLT', 'GREEN', '17', 'PARIS');
INSERT INTO `parts`.`parttable` (`P_ID`, `PNAME`, `COLOUR`, `WEIGHT`, `CITY`) VALUES ('P3', 'SCREW', 'BLUE', '17', 'ROME');
INSERT INTO `parts`.`parttable` (`P_ID`, `PNAME`, `COLOUR`, `WEIGHT`, `CITY`) VALUES ('P4', 'SCREW', 'RED', '14', 'LONDON');
INSERT INTO `parts`.`parttable` (`P_ID`, `PNAME`, `COLOUR`, `WEIGHT`, `CITY`) VALUES ('P5', 'CAW', 'BLUE', '12', 'PARIS');
INSERT INTO `parts`.`parttable` (`P_ID`, `PNAME`, `COLOUR`, `WEIGHT`, `CITY`) VALUES ('P6', 'COG', 'RED', '19', 'LONDON');

CREATE TABLE PROJECT(
J_ID VARCHAR(50),
JNAME VARCHAR(80),
CITY VARCHAR(50)
);
INSERT INTO PROJECT
(J_ID, JNAME, CITY)
VALUES
('J1', 'SORTER' , 'PARIS'),
('J2', 'DISPLAY', 'ROME'),
('J3', 'OCR',  'ATHENS'),
('J4', 'CONSOLE','ATHENS'),
('J5', 'RAID', 'LONDON'),
('J6', 'EDS', 'OSLO'),
('J7', 'TAPE', 'LONDON')
;

CREATE TABLE SUPPLIER(
S_ID VARCHAR(50),
SNAME VARCHAR(80),
STATUS INT,
CITY VARCHAR(50)
);
INSERT INTO SUPPLIER
(S_ID, SNAME, STATUS, CITY)
VALUES
('S1', 'SMITH', 20, 'LONDON'),
('S2', 'JONES', 10, 'PARIS'),
('S3', 'BLAKE', 30, 'PARIS'),
('S4', 'CLARK', 20, 'LONDON'),
('S5', 'ADAM', 30, 'ATHENS')
;

